CREATE TABLE IF NOT EXISTS DAMAGE_REPORT_MAIL (
    MESSAGE_ID TEXT NOT NULL,
    ATTACK_DATE TEXT,
    OPPOSITE_AGENT_NAME TEXT,
    CREATE_DATE TEXT,
    PRIMARY KEY(MESSAGE_ID)
);
CREATE TABLE IF NOT EXISTS DAMAGE_PORTAL (
    MESSAGE_ID TEXT NOT NULL,
    SEQ INTEGER NOT NULL,
    PORTAL_NAME TEXT NOT NULL,
    PORTAL_INTEL_URL TEXT NOT NULL,
    LONGITUDE TEXT, 
    LATITUDE TEXT,
    CREATE_DATE TEXT,
    PRIMARY KEY(MESSAGE_ID, SEQ)
);
